### ISSUE TITLE
トップページの新着が流れていってしまう問題を改善する

### ISSUE THREAD

**Issue by thanks2music** [thanks2music/revenge#139]
トップページのレイアウトを改修する

### TODO

- [ ] SP) ロゴ下にカテゴリメニューを設ける
- [ ] PC/SP) ジャンル毎に記事を表示する
- [ ] PC/SP) 人気作品の記事だけ別に出す
- [ ] SP) 人気作品はトップページに新着記事を横スクロール表示にする
- [ ] PC/SP) 管理画面から作品やジャンルを変更出来るようにする
